<?php

    function mymodule_menu()
    {
        $items['path-to-ajax/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'mymodule_ajax_callback',
            'page arguments' => array(1, 2),
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function module_ajax_callback($js, $node_id)
    {
        $node = node_load($node_id);

        //Redirects to content page if JavaScript is not available
        if($js == 'nojs'){
            drupal_goto('node/', $node->nid);
        }

        //Get the render array for the node, and render it into HTML
        $build = node_view($node);
        $html = render($build);

        //Prepare ajax command to insert the node's HTML into home page wrapper
        $commands = array();
        $commands[] = ajax_command_html('#mymodule-ajax-wrapper', $html);

        //Render commands into JSON data format execute them by printing to the browser
        print ajax_render($commands);
        drupal_set_message("am I working?");
        exit;











    }
